version: "3.5"

services:
  postgres-elcompbase:
    container_name: postgres-elcompbase
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./.docker-volumes/postgres:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      elcompbase-net:
        ipv4_address: 172.28.1.1

  liquibase-elcompbase:
    container_name: liquibase-elcompbase
    image: liquibase/liquibase:${LIQUIBASE_VERSION}
    restart: on-failure
    command: --defaultsFile=liquibase.properties update
    depends_on:
      - postgres-elcompbase
    volumes:
      - ./db/:/liquibase/changelog/
      - ./db/:/liquibase/classpath/
      - ./db/liquibase.properties:/liquibase/liquibase.properties
    networks:
      elcompbase-net:
        ipv4_address: 172.28.1.2

  elcompbase-app:
    container_name: elcompbase-app
    build: ./
#    restart: on-failure
    env_file:
      - .env
    depends_on:
      - postgres-elcompbase
    ports:
      - ${APP_PORT}:9000
    networks:
      elcompbase-net:
        ipv4_address: 172.28.1.3

networks:
  elcompbase-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16