debug: ${SPRING_DEBUG:false}
server:
  port: ${APP_PORT:9000}
  forward-headers-strategy: framework
  tomcat:
    threads:
      max: 5000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 25
      minimum-idle: 2
      max-lifetime: 120000
      idle-timeout: 300000
    url: ${POSTGRES_URL}?currentSchema=${POSTGRES_SCHEMA:elcompbase}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    tomcat:
      jdbc-interceptors: "org.apache.tomcat.jdbc.pool.interceptor.QueryTimeoutInterceptor(queryTimeout=5);org.apache.tomcat.jdbc.pool.interceptor.SlowQueryReport(threshold=1000,maxQueries=200)"
  application:
    name: elcompbase

cache:
  user-maximum-size: 100000
  user-expired-time-hours: 4

app:
  url: ${APP_URL}
  api-path: ${API_PATH:/}
  salt: ${HASH_SALT}
  jwt-signing-key: ${JWT_SIGNING_KEY}
  token-ttl: ${TOKEN_TTL:4}